# gSpace application settings
gspace.base.dir=c:\\Geomage\\gSpace
gspace.exe.name=gSpace.exe
gspace.splash.wait=3000
gspace.main.window.wait=5000

# SikuliX settings
image.dir=images

# Application detection
app.logo.folder=001_logo

# Test settings
menu.image.folder=002_menu
ribbon.image.folder=003_ribbon